version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    build:
      context: '.'
      dockerfile: 'db.Dockerfile'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: review_data
    volumes:
      - review-data:/var/lib/postgresql/data
volumes:
  review-data:
